scale_list = [
    'Extremely important',
    'Enjoyed a lot',
    'Extremely knowledgeable',
    'I will definitely recommend the show',
    'A lot',
    'I would definitely recommend this show',
    'Extremely well',
    'Very involved',
    'Excellent',
    'I see way too much',
    'Completely describes',
    'It is very important to me',
    'I love it',
    'I\'m very excited',
    'Completely agree',
    'One of my favourites',
    'Much more positive',
    'I am more interested in the world of Fortnite',
    'I am much more excited to play',
    'Very relevant',
    'Make me much more likely to try it',
    'It\'s much more relevant for people like me',
    '5 - It\'s one of my favorites',
    '5 - Enjoy a lot',
    'Very often',
    'Greatly increased',
    'Feel much more positive',
    'Fits extremely well',
    'One of your favorites',
    'Make every effort to watch future episodes',
    'Definitely would sign-up',
    'Very conservative',
    'Definitely would take my child to see it',
    'I will make every effort to watch',
    'Much better',
    'Very Open',
    'Fits very well',
    'All the time',
    'Extremely valuable',
    'Definitely post something, in a positive way',
    'Definitely talk about it, in a positive way',
    'Much more favourable',
    'A lot more interested',
    'This is a very big problem in our country today',
    'Very positive',
    'Very closely',
    'watch as soon as it is released',
    'Very fresh and original',
    'Extremely interested',
    'Extremely familiar',
    'Describes me completely',
    'Like them a lot',
    'Strongly agree',
    'I definitely would watch',
    'Definitely would be interested',
    'Very interested',
    'Extremely influential',
    'Much too expensive',
    'Extremely satisfied',
    'Extremely easy',
    'Extremely open',
    'I understand it completely',
    'Extremely closely',
    'Increase a lot',
    'Extremely likely',
    'Extremely unique and different',
    'Love them',
    'I am very interested',
    'Extremely excited',
    'Very excited',
    'Very satisfied',
    'Agree Strongly',
    'It makes a lot of impact',
    'I currently use it',
    'Enjoyed very much',
    'Completely Agree',
    'much more interested',
    'Strongly',
    'Definitely will',
    'Currently use',
    'Very interested',
    'Very important',
    'Definitely would see it',
    'Excellent',
    'Extremely interested',
    'Very Interested',
    '1 -',
    'All of my time is spent watching shows',
    'Completely describes why I watch my favorite TV series and movies' 
    'Watched many episodes of the show',
    'Definitely would watch it',
    'Love it',
    '5 -',
    'Applies completely',
    'Very clear',
    'Agree',
    'I will make every effort to watch future episodes',
    'Watch as soon as it is released',
    'I\'m very familiar',
    'I\'m a big fan',
    'Enjoy a lot',
    'It\'s one of my favorites',
    'Very likely',
    'Very Likely',
    'I have watched all of the episodes',
    'Liberal',
    'One of my favorites',
    'I watched this show//event for the first time in 2020',
    'I\'ve watched this many times',
    'It\'s one of my favorites',
    'At the top of its game',
    'Completely motivates me to watch the show',
    'I would make every effort to watch',
    'Very unique and original',
    'I am a big fan',
    'I watch this every year',
    'Everyday',
    'At least daily',
    'Very optimistic',
    'I\'m watching a lot more',
    'Yes, I\'m a big fan',
    'Definitely would watch',
    'Makes me think much more',
    'Makes me much more likely',
    'Absolutely certain to see',
    'Much more likely',
    '7 - Highly favorable',
    '7 - Much more favorable',
    'Definitely would purchase',
    'I will make every effort to watch it',
    'Definitely would recommend',
    'Liked it a lot',
    'Very well',
    'Loved it',
    'Much more favorable',
    'Very favorable',
    'Trust completely',
    'Very familiar',
    'Always',
    'Definitely would use',
    'I understand them completely',
    'Extremely important',
    'Extremely well',
    'Extremely concerned',
    'I know a lot about it',
    'Very dissatisfied',
    'I like it a lot',
    'Definitely interested',
    'Like it a lot',
    'Definitely would subscribe',
    'Makes me very interested in subscribing',
    'Like it a lot'
]

nor = ["Else", "None of the above", "Other", "None of these", "Prefer not to specify", "I don't know", "Not sure",
       "Prefer not to answer","No opinion"]
szr = ["No Response"]
